name: Make API Request

on:
  push:
    branches:
      - main

jobs:
  make-api-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://663dd86ce1913c4767959d4c.mockapi.io/test/v1/test1'
          customHeaders: '{"Content-Type":"application/json"}'
          method: 'GET'

      - name: Show API Response Status
        run: |
          echo "Response Status: ${{ steps.api-request.outputs.status }}"

      - name: Show API Response Data
        run: |
          echo "Response Data: ${{ steps.api-request.outputs.response }}"