name: Make API Request

on:
  pull_request_review:
    types: [submitted]


jobs:

  post-approval-check-test:
    name: 'Post Approval Check in Test'

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    if: ${{ github.event.review.state == 'approved' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Make Request Script
        run: python devops/make_request.py
        shell: sh

      - name: Post Test Success
        run: echo "Tests Succeeded"
        