name: Make API Request

on:
  pull_request_review:
    types: [submitted]


jobs:
  make-api-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Make Request Script
        run: python devops/make_request.py
        shell: sh

      - name: Post Test Success
        run: echo "Tests Succeeded"